"""Add-created-date

Revision ID: 75f8e4d552c6
Revises: a4bee09ca259
Create Date: 2025-10-31 23:34:42.869975

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '75f8e4d552c6'
down_revision = 'a4bee09ca259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designitem', sa.Column('created_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designitem', 'created_date')
    # ### end Alembic commands ###
