"""Add-cascade-delete

Revision ID: 7fb594835880
Revises: 75f8e4d552c6
Create Date: 2025-11-02 17:41:00.377694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7fb594835880'
down_revision = '75f8e4d552c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usercompanylink_company_id_fkey'), 'usercompanylink', type_='foreignkey')
    op.create_foreign_key(None, 'usercompanylink', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usercompanylink', type_='foreignkey')
    op.create_foreign_key(op.f('usercompanylink_company_id_fkey'), 'usercompanylink', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
