"""Add initial data

Revision ID: a4bee09ca259
Revises: 1a31ce608336
Create Date: 2025-10-30 11:40:39.939977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a4bee09ca259'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('status', sa.Enum('public', 'private',
                                                name='companystatus'), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('designitem',
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('creator_id', sa.Uuid(), nullable=False),
                    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(
                        length=511), nullable=False),
                    sa.Column('preview_path', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['company.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tag',
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(
                        length=31), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['company.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('usercompanylink',
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('role', sa.Enum('reader', 'creator', 'owner',
                                              name='companyrole'), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('company_id', 'user_id')
                    )
    op.create_table('tagitemlink',
                    sa.Column('design_item_id', sa.Uuid(), nullable=False),
                    sa.Column('tag_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['design_item_id'], ['designitem.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                    sa.PrimaryKeyConstraint('design_item_id', 'tag_id')
                    )
    op.add_column('user', sa.Column('is_delited', sa.Boolean(),
                  nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delited')
    op.drop_table('tagitemlink')
    op.drop_table('usercompanylink')
    op.drop_table('tag')
    op.drop_table('designitem')
    op.drop_table('company')
    # ### end Alembic commands ###
