"""Make tag title unique ignorecase

Revision ID: ecb5da9dc187
Revises: 7fb594835880
Create Date: 2025-11-17 23:10:14.668757

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ecb5da9dc187'
down_revision = '7fb594835880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tag_title_lower', 'tag', [sa.literal_column('LOWER(title)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tag_title_lower', table_name='tag')
    # ### end Alembic commands ###
